### ISSUE TITLE
Cannot read the p12 file 

### ISSUE THREAD

**Issue by bipinkh** [eideasy/cef-esignature-building-block-samples#1]
Tried running the code as it is and triggered the endpoint. I get the following error:

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is eu.europa.esig.dss.model.DSSException: Unable to instantiate KeyStoreSignatureTokenConnection] with root cause

java.io.IOException: Short read of DER length
```

Stacktrace - https://pastebin.com/NqegEBug

**Comment by smartman** [comment]
Are you sure your p12 file is correct? This is quite low level Java function and very likely that the p12 file is invalid, this is what   "Short read of DER length"  error means.

**Comment by bipinkh** [comment]
> Are you sure your p12 file is correct? This is quite low level Java function and very likely that the p12 file is invalid, this is what "Short read of DER length" error means.

Yes, I used the same p12 file that is present inside the resources folder. Also, tried using another p12 file but could not succeed.

**Comment by smartman** [comment]
You are right. Somehow the p12 had 0 bytes. Now there is valid keystore and signing works. Please do notify if you have any other challenges with you eSignature project.
